# -*- coding: utf-8 -*-
"""健康外食Go.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAXbIK1Zg0SfffkkjeRe2Y2lPRpkExGT
"""

!pip install line-bot-sdk

from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, LocationMessage, LocationSendMessage
import requests
import os

app = Flask(__name__)

# 設定Line Bot的API和Handler
line_bot_api = LineBotApi(os.getenv('LINE_CHANNEL_ACCESS_TOKEN'))
handler = WebhookHandler(os.getenv('LINE_CHANNEL_SECRET'))

NOMINATIM_SEARCH_URL = 'https://nominatim.openstreetmap.org/search'

@app.route("/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    if event.message.text == '我想取得周遭健康外食':
        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text="我看到了")
        )
        # 觸發使用者傳送位置的請求
        message = LocationSendMessage(
            title='請分享您的位置',
            address='您的位置',
            latitude=25.033,
            longitude=121.565
        )
        line_bot_api.push_message(
            event.source.user_id,
            message
        )

@handler.add(MessageEvent, message=LocationMessage)
def handle_location(event):
    latitude = event.message.latitude
    longitude = event.message.longitude
    restaurants = find_health_restaurants(latitude, longitude)

    if restaurants:
        reply_message = "附近的健康外食餐廳：\n"
        for restaurant in restaurants:
            reply_message += f"{restaurant['display_name']}\n"
            reply_message += f"地址：{restaurant['address']}\n"
            reply_message += "\n"
    else:
        reply_message = "附近沒有找到健康外食餐廳。"

    line_bot_api.reply_message(
        event.reply_token,
        [
            TextSendMessage(text=reply_message),
            TextSendMessage(text="已收到您的位置，開始搜尋餐廳...")
        ]
    )

def find_health_restaurants(latitude, longitude):
    params = {
        'format': 'json',
        'q': 'restaurant',
        'viewbox': f"{longitude-0.05},{latitude-0.05},{longitude+0.05},{latitude+0.05}",
        'bounded': 1,
        'limit': 10
    }
    response = requests.get(NOMINATIM_SEARCH_URL, params=params)
    results = response.json()
    # 篩選出餐廳
    restaurants = [result for result in results if 'restaurant' in result['type']]
    return restaurants

# 設定環境變數
os.environ['CHANNEL_ACCESS<|disc_sep|>

請確保你已將 `YOUR_CHANNEL_ACCESS_TOKEN` 和 `YOUR_CHANNEL_SECRET` 替換為你的Line Bot的Channel Access Token和Channel Secret。

# 啟動Flask App
app.run(host='0.0.0.0', port=5000)
